# -*- coding: utf-8 -*-
"""ML_First_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUgrgDn-msVuBdMrqYNL-mg0wHGHIdW-
"""

# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


dataset= pd.read_csv('WildBlueberryPollinationSimulationData.csv')
print(dataset)



# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,1:17].values
# Extracting dependent variable:
y = dataset.iloc[:, 17].values



from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
model1 = RandomForestRegressor()
model1.fit(X_train, y_train)






